name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-2019]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the Latest Package Code
        uses: actions/checkout@v3
      - name: Setup Pulsar Editor
        uses: pulsar-edit/action-pulsar-dependency@21daf27cea22daed15f682cd4146b2e3a57b0d6c
        with:
          package-to-test: "autocomplete-plus"
      - name: Run the headless Pulsar Tests
        uses: GabrielBB/xvfb-action@v1
        with:
          # What if we match Pulsar Package Tests?
          run: node -e "require('./script/run-package-tests')('autocomplete-plus')"
          working-directory: ./pulsar
